import io, os, cairosvg
from PIL import Image, ImageDraw, ImageFont
from marks import wrap, CONCEPTS, SPARK, INK, VOLT, WHITE

os.makedirs("svg", exist_ok=True); os.makedirs("png", exist_ok=True)
def png(svgtxt, px):
    return Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svgtxt.encode(), output_width=px, output_height=px))).convert("RGBA")
def save_svg(name, txt):
    open(f"svg/{name}.svg", "w").write(txt)

# ---------- files for every concept ----------
for name, d, _ in CONCEPTS:
    slug = name.lower().replace(" ", "-")
    save_svg(f"concept-{slug}", wrap(d, INK))

# ---------- full kit for the recommended mark ----------
kit = {
    "js17-mark-black": wrap(SPARK, INK),
    "js17-mark-white": wrap(SPARK, WHITE),
    "js17-mark-volt": wrap(SPARK, VOLT),
    "js17-app-icon": wrap(SPARK, VOLT, bg=INK, pad=24, rx=30),
    "js17-app-icon-light": wrap(SPARK, INK, bg=VOLT, pad=24, rx=30),
    "js17-favicon": wrap(SPARK, VOLT, bg=INK, pad=14, rx=22),
}
for k, v in kit.items():
    save_svg(k, v)
for k in ["js17-mark-black", "js17-mark-white", "js17-mark-volt"]:
    png(kit[k], 1024).save(f"png/{k}-1024.png")
for s in [1024, 512, 180]:
    png(kit["js17-app-icon"], s).save(f"png/js17-app-icon-{s}.png")
for s in [16, 32, 48]:
    png(kit["js17-favicon"], s).save(f"png/js17-favicon-{s}.png")
png(kit["js17-favicon"], 256).save("favicon.ico", sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])

# ---------- presentation board ----------
B = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
R = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
f_title, f_h, f_b, f_s = (ImageFont.truetype(B, 54), ImageFont.truetype(B, 34),
                          ImageFont.truetype(R, 24), ImageFont.truetype(R, 20))
W, H = 2400, 1830
bd = Image.new("RGB", (W, H), "white")
d = ImageDraw.Draw(bd)
def paste(img, xy): bd.paste(img, xy, img)

d.text((90, 70), "js.17 · logo concepts", fill=INK, font=f_title)
d.text((90, 140), "No text in the mark. One colour, works from a billboard down to a 16 px browser tab.", fill="#555555", font=f_b)

colw = 740
for i, (name, dpath, idea) in enumerate(CONCEPTS):
    x = 90 + i * colw
    if i == 0:
        d.rounded_rectangle((x - 30, 210, x + colw - 70, 1180), radius=28, outline=INK, width=3)
        d.rounded_rectangle((x + colw - 300, 228, x + colw - 92, 272), radius=20, fill=VOLT)
        d.text((x + colw - 282, 233), "Recommended", fill=INK, font=ImageFont.truetype(B, 24))
    d.text((x, 230), f"{i + 1}. {name}", fill=INK, font=f_h)
    d.text((x, 280), idea, fill="#555555", font=f_b)
    paste(png(wrap(dpath, INK), 420), (x + 110, 340))
    paste(png(wrap(dpath, VOLT, bg=INK, pad=24, rx=30), 250), (x, 800))
    paste(png(wrap(dpath, INK, bg=VOLT, pad=24, rx=30), 250), (x + 300, 800))
    for j, s in enumerate([48, 32, 16]):
        paste(png(wrap(dpath, VOLT, bg=INK, pad=14, rx=22), s), (x + j * 80, 1090 - s // 2))
    d.text((x + 250, 1078), "favicon at 48 / 32 / 16 px", fill="#777777", font=f_s)

# usage row for the recommended mark
y0 = 1250
d.text((90, y0), "Spark Block in use", fill=INK, font=f_h)
# browser tab mock
d.rounded_rectangle((90, y0 + 70, 900, y0 + 300), radius=18, fill="#ECECEC")
d.rounded_rectangle((110, y0 + 90, 520, y0 + 150), radius=12, fill="white")
paste(png(kit["js17-favicon"], 32), (130, y0 + 104))
d.text((178, y0 + 105), "js.17: award-winning sites, by AI", fill=INK, font=f_s)
d.rounded_rectangle((110, y0 + 170, 880, y0 + 280), radius=10, fill="white")
paste(png(wrap(SPARK, INK), 46), (140, y0 + 202))
d.text((200, y0 + 205), "js.17", fill=INK, font=ImageFont.truetype(B, 34))
for xx, item in [(470, "Showcase"), (590, "Pricing")]:
    d.text((xx, y0 + 212), item, fill=INK, font=f_s)
d.rounded_rectangle((690, y0 + 200, 862, y0 + 250), radius=25, fill=INK)
d.text((708, y0 + 212), "Start building", fill=VOLT, font=f_s)
# app icons
paste(png(kit["js17-app-icon"], 230), (990, y0 + 70))
paste(png(kit["js17-app-icon-light"], 230), (1250, y0 + 70))
# dark hero mock
d.rounded_rectangle((1530, y0 + 70, 2310, y0 + 300), radius=18, fill=INK)
paste(png(wrap(SPARK, VOLT), 120), (1580, y0 + 125))
d.text((1730, y0 + 130), "Sites that win awards,", fill=WHITE, font=ImageFont.truetype(B, 36))
d.text((1730, y0 + 180), "generated by AI.", fill=VOLT, font=ImageFont.truetype(B, 36))
# palette
y1 = y0 + 360
d.text((90, y1), "Colours", fill=INK, font=f_h)
for k, (nm, hx, txt) in enumerate([("Ink", INK, WHITE), ("Volt", VOLT, INK), ("Paper", WHITE, INK)]):
    xx = 90 + k * 300
    d.rounded_rectangle((xx, y1 + 60, xx + 270, y1 + 200), radius=16, fill=hx, outline="#D0D0D0", width=2)
    d.text((xx + 20, y1 + 140), f"{nm}  {hx}", fill=txt, font=f_b)
d.text((1000, y1 + 70), "Volt lime stands apart from competitors' colours (Framer black, Base44 orange)", fill="#555555", font=f_b)
d.text((1000, y1 + 110), "and from the purple-and-blue gradients most AI brands use.", fill="#555555", font=f_b)
bd.save("js17-logo-board.png")
print("built")
